// RED PLAYER
export enum ActionType {
  UPDATE_RED_NAME = "UPDATE_RED_NAME",
  ADD_RED_SCORE = "ADD_RED_SCORE",
  SUB_RED_SCORE = "SUB_RED_SCORE",
  ADD_RED_EXIT = "ADD_RED_EXIT",
  SUB_RED_EXIT = "SUB_RED_EXIT",
  ADD_RED_WARN = "ADD_RED_WARN",
  SUB_RED_WARN = "SUB_RED_WARN",

// BLUE PLAYER
  UPDATE_BLUE_NAME = "UPDATE_BLUE_NAME",
  ADD_BLUE_SCORE = "ADD_BLUE_SCORE",
  SUB_BLUE_SCORE = "SUB_BLUE_SCORE",
  ADD_BLUE_EXIT = "ADD_BLUE_EXIT",
  SUB_BLUE_EXIT = "SUB_BLUE_EXIT",
  ADD_BLUE_WARN = "ADD_BLUE_WARN",
  SUB_BLUE_WARN = "SUB_BLUE_WARN",

// GAME
  UPDATE_GAME_TITLE = "UPDATE_GAME_TITLE",
  UPDATE_GAME_TIME = "UPDATE_GAME_TIME",
  END_GAME = "END_GAME",
  SET_WINNER = "SET_WINNER",
  START_GAME_TIME = "START_GAME_TIME",
  PAUSE_GAME_TIME = "PAUSE_GAME_TIME",
  SAVE_DEFAULT = "SAVE_DEFAULT",
  RESTORE_DEFAULT = "RESTORE_DEFAULT",
}

export type Action = {
  type: ActionType
  payload?: any
}
